### ISSUE TITLE
config for client

### ISSUE THREAD

**Issue by chris669** [LJea/openvpn-auth-ldap-win#1]
Hi, I tried your solution, totally newbie, sorry, installed the two files in admin folder and wrote this on the server.ovpn:

`script-security 3
auth-user-pass-verify WindowsADLogin.exe via-env`

(different from your readme)
but what do I have to write on client side?
**EDIT:**
On client side:
`auth-user-pass
auth-nocache
`
Another point, what's this line for if your program check password in AD?
`<add key="Password" value="1234abcd!@#$"></add>`

thanks.

**Comment by Boc-chi-no** [comment]
The readme file is different because I changed the name of the assembly after the latest version, and Now I will recompile the latest release
I noticed "script-security 3 (**whether line breaks are missing??**) auth-user-pass-verify WindowsADLogin.exe via-env"
You need to open the log in openvpn-auth-ldap.exe.config and attach the log of LoginLog folder, if not then openvpn-auth-ldap may not be running
This password is used by the delegate to query the inheritance relationship
[https://mc.lioat.cn/2019/12/0055133.xhtml](https://mc.lioat.cn/2019/12/0055133.xhtml), This is a description of this plugin, but it is in Chinese

**Comment by chris669** [comment]
Yes, line breaks disappeared after pasting it(?). Do this password must not be changed?
Anyway, it's working great, tested it on my WS2019 essentials. Any others points I should care about security? Still looking for a solution including Google Authenticator, but I think it's not available for the windows server version. Anyway, thanks a lot sharing your code!

**Comment by Boc-chi-no** [comment]
Sorry, I didn't explain clearly in the end due to Google Translate

InheritanceDetection: whether to allow inherited access
ReadGroupUser: Users with read-only access to user groups (only when InheritanceDetection is True)
Password: Password for this user (InheritanceDetection is True only)

You need to create a user and grant the user read user/group permissions via Delegated Control, this is the most secure Or use the domain admin user directly, but this is extremely insecure because the configuration file is clear text and you may leak the administrator password

I may add 2FA functionality in a future release

**Comment by chris669** [comment]
Hi, you say: "configuration file is clear text" this is only for Inheritance detection between openVPN server and AD Server, right? The user and password from the client are always encrypted in the VPN tunnel, right? Sorry for my basic knowledge... So as I don't need Inheritance option, seems ok for me. A nice day. Chris

**Comment by chris669** [comment]
Sorry but you forgot to put the compiled .exe file?

**Comment by Boc-chi-no** [comment]
[You can download the latest releases](https://github.com/LJea/openvpn-auth-ldap-win/releases/tag/1.1)
Yes, The user and password from the client are always encrypted in the VPN tunnel, but you need to note that the current version of openvpn-auth-ldap passes passwords through environment variables.(Openvpn->(env)-> openvpn-auth -ldap)
If your server is safe, then this is not a big problem
